AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Lambda:
  EnforcedStyle: literal

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 35

Metrics/ModuleLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Layout/LineLength:
  Max: 140

Style/Documentation:
  Enabled: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
